/*
 * Copyright © 2018 Christian Persch
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#if !defined(_BTE_OSC)
#error "Must define _BTE_OSC before including this file"
#endif

/* _BTE_OSC(DTTERM_CWD, 3) Conflicts with XTERM_SET_XPROPERTY */

_BTE_OSC(EMACS_51, 51)

_BTE_OSC(ITERM2_GROWL, 9)
_BTE_OSC(ITERM2_133, 133)
_BTE_OSC(ITERM2_1337, 1337)

_BTE_OSC(KONSOLE_30, 30)
_BTE_OSC(KONSOLE_31, 31)

/* _BTE_OSC(MINTTY_CLIPBOARD_COPY_WINDOW_TITLE,    7721) */
/* _BTE_OSC(MINTTY_CHANGE_FONT_SIZE,               7770) */
/* _BTE_OSC(MINTTY_QUERY_FONT_SUPPORTS_CHARACTERS, 7771) */
/* _BTE_OSC(MINTTY_CHANGE_FONT_AND_WINDOW_SIZE,    7777) */
/* _BTE_OSC(MINTTY_INDIC_WIDE, 77119) out of range */

_BTE_OSC(RLOGIN_SET_KANJI_MODE, 800)
_BTE_OSC(RLOGIN_SPEECH, 801)

/* _BTE_OSC(RXVT_MENU, 10) * Conflics with XTERM_SET_COLOR_TEXT_FG */
_BTE_OSC(RXVT_SET_BACKGROUND_PIXMAP, 20)
_BTE_OSC(RXVT_SET_COLOR_FG, 39)
_BTE_OSC(RXVT_SET_COLOR_BG, 49)
_BTE_OSC(RXVT_DUMP_SCREEN, 55)

_BTE_OSC(URXVT_SET_LOCALE, 701)
_BTE_OSC(URXVT_VERSION, 702)
_BTE_OSC(URXVT_SET_COLOR_TEXT_ITALIC, 704)
_BTE_OSC(URXVT_SET_COLOR_TEXT_BOLD, 706)
_BTE_OSC(URXVT_SET_COLOR_UNDERLINE, 707)
_BTE_OSC(URXVT_SET_COLOR_BORDER, 708)
_BTE_OSC(URXVT_SET_FONT, 710)
_BTE_OSC(URXVT_SET_FONT_BOLD, 711)
_BTE_OSC(URXVT_SET_FONT_ITALIC, 712)
_BTE_OSC(URXVT_SET_FONT_BOLD_ITALIC, 713)
_BTE_OSC(URXVT_VIEW_UP, 720)
_BTE_OSC(URXVT_VIEW_DOWN, 721)
_BTE_OSC(URXVT_EXTENSION, 777)

_BTE_OSC(BTECWF, 6)
_BTE_OSC(BTECWD, 7)
_BTE_OSC(BTEHYPER, 8)

_BTE_OSC(XTERM_SET_WINDOW_AND_ICON_TITLE, 0)
_BTE_OSC(XTERM_SET_ICON_TITLE, 1)
_BTE_OSC(XTERM_SET_WINDOW_TITLE, 2)
_BTE_OSC(XTERM_SET_XPROPERTY, 3)
_BTE_OSC(XTERM_SET_COLOR, 4)
_BTE_OSC(XTERM_SET_COLOR_SPECIAL, 5)
/* _BTE_OSC(XTERM_SET_COLOR_MODE, 6) Conflict with our own OSC 6 BTECWF; so use 106 */
_BTE_OSC(XTERM_SET_COLOR_TEXT_FG, 10)
_BTE_OSC(XTERM_SET_COLOR_TEXT_BG, 11)
_BTE_OSC(XTERM_SET_COLOR_CURSOR_BG, 12)
_BTE_OSC(XTERM_SET_COLOR_MOUSE_CURSOR_FG, 13)
_BTE_OSC(XTERM_SET_COLOR_MOUSE_CURSOR_BG, 14)
_BTE_OSC(XTERM_SET_COLOR_TEK_FG, 15)
_BTE_OSC(XTERM_SET_COLOR_TEK_BG, 16)
_BTE_OSC(XTERM_SET_COLOR_HIGHLIGHT_BG, 17)
_BTE_OSC(XTERM_SET_COLOR_TEK_CURSOR, 18)
_BTE_OSC(XTERM_SET_COLOR_HIGHLIGHT_FG, 19)
_BTE_OSC(XTERM_LOGFILE, 46)
_BTE_OSC(XTERM_SET_FONT, 50)
_BTE_OSC(XTERM_SET_XSELECTION, 52)
_BTE_OSC(XTERM_RESET_COLOR, 104)
_BTE_OSC(XTERM_RESET_COLOR_SPECIAL, 105)
_BTE_OSC(XTERM_SET_COLOR_MODE, 106)
_BTE_OSC(XTERM_RESET_COLOR_TEXT_FG, 110)
_BTE_OSC(XTERM_RESET_COLOR_TEXT_BG, 111)
_BTE_OSC(XTERM_RESET_COLOR_CURSOR_BG, 112)
_BTE_OSC(XTERM_RESET_COLOR_MOUSE_CURSOR_FG, 113)
_BTE_OSC(XTERM_RESET_COLOR_MOUSE_CURSOR_BG, 114)
_BTE_OSC(XTERM_RESET_COLOR_TEK_FG, 115)
_BTE_OSC(XTERM_RESET_COLOR_TEK_BG, 116)
_BTE_OSC(XTERM_RESET_COLOR_HIGHLIGHT_BG, 117)
_BTE_OSC(XTERM_RESET_COLOR_TEK_CURSOR, 118)
_BTE_OSC(XTERM_RESET_COLOR_HIGHLIGHT_FG, 119)

_BTE_OSC(YF_RQGWR, 8900)
